name: Laravel CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      # Add MySQL service
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fitness
          MYSQL_USER: laravel
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysql, xml, ctype, iconv, intl, json, tokenizer
          coverage: none

      - name: Copy .env
        run: |
          cp .env.example .env
          echo "APP_KEY=" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=fitness" >> .env
          echo "DB_USERNAME=laravel" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create Database
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS fitness;"
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "CREATE USER IF NOT EXISTS 'laravel'@'%' IDENTIFIED BY 'password';"
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "GRANT ALL PRIVILEGES ON fitness.* TO 'laravel'@'%';"
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "FLUSH PRIVILEGES;"

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Execute Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: fitness
          DB_USERNAME: laravel
          DB_PASSWORD: password
        run: vendor/bin/phpunit --testdox

      - name: Upload Artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: storage/logs/
